#!/usr/bin/env bash
# Install the OUTBOUND half of the second recovery direction (Rev 3 sections 5.2, 5.4).
#
# Runs ON dial-hermes-control. It generates a dedicated keypair, wires SSH to use it for
# the E2 targets and nothing else, and prints the public key for the owner to carry to
# each E2 (where install-bounded-recovery-identity.sh binds it to the forced command).
#
#   install-bounded-recovery-peer.sh            # generate + wire + print the public key
#   install-bounded-recovery-peer.sh --print    # print the public key again
#   install-bounded-recovery-peer.sh --verify   # report, change nothing
#   install-bounded-recovery-peer.sh --remove   # delete the key and the config block
#
# It never touches the E2 -> Hermes direction, and it never asks for or moves a private
# key. The private half is generated here and stays here.

set -uo pipefail

FABRIC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST_ID="${DIAL_FABRIC_HOST_ID:-$(hostname)}"
SSH_DIR="${DIAL_SSH_DIR:-$HOME/.ssh}"
KEY="$SSH_DIR/dial-bounded-recovery"
CONFIG="$SSH_DIR/config"
SSH_USER="${DIAL_FABRIC_SSH_USER:-ubuntu}"
BEGIN="# >>> dial-bounded-recovery (managed) >>>"
END="# <<< dial-bounded-recovery (managed) <<<"

die() { echo "install-bounded-recovery-peer: $*" >&2; exit 1; }

# ssh-keygen is checked at the point of use, not here. Refusing on a missing tool before
# checking the role would answer "wrong host" with "wrong tool", which sends an operator
# installing packages on a machine that should never run this at all.

# --- Who may hold the outbound half --------------------------------------------------
# Only the BOUNDED_RECOVERY host. Running this on an E2 would give a recovery peer a
# second, differently-scoped key into its partner for no reason, and reusing one identity
# for both directions is precisely what section 5.4 rule 1 forbids.
# A command substitution, not a process substitution: `mapfile ... < <(cmd) || die`
# cannot work, because mapfile succeeds with zero lines however cmd exited, and the
# refusal below would never be reached.
targets_raw="$(node -e '
  const f = require(process.argv[1]);
  const self = f.hosts.find((h) => h.host_id === process.argv[2]);
  if (!self || !self.roles.includes("BOUNDED_RECOVERY")) process.exit(2);
  for (const t of self.recovers) {
    const key = `DIAL_FABRIC_${t.toUpperCase().replace(/-/g, "_")}_SSH_HOST`;
    const addr = process.env[key] || (f.hosts.find((h) => h.host_id === t) || {}).private_ip;
    if (addr) process.stdout.write(`${t} ${addr}\n`);
  }
' "$FABRIC_DIR/hosts.json" "$HOST_ID" 2>/dev/null)" \
  || die "$HOST_ID does not hold the BOUNDED_RECOVERY role; refusing.
The outbound half belongs on the control host only. On an E2, you want
install-bounded-recovery-identity.sh instead."

mapfile -t TARGETS <<<"$targets_raw"
[[ ${#TARGETS[@]} -gt 0 && -n "${TARGETS[0]:-}" ]] || die "no recovery targets in hosts.json"

mkdir -p "$SSH_DIR" && chmod 700 "$SSH_DIR"

config_block() {
  { echo "$BEGIN"
    echo "# Generated by install-bounded-recovery-peer.sh. Edit hosts.json, not this."
    echo "# IdentitiesOnly is load-bearing: without it ssh may offer this host's OTHER"
    echo "# keys first, and the E2 would authorize whichever one it recognises — which"
    echo "# could be an unrestricted identity rather than the forced-command one."
    for row in "${TARGETS[@]}"; do
      read -r target addr <<<"$row"
      echo "Host $target $addr"
      echo "    HostName $addr"
      echo "    User $SSH_USER"
      echo "    IdentityFile $KEY"
      echo "    IdentitiesOnly yes"
      echo "    StrictHostKeyChecking yes"
      echo "    BatchMode yes"
      echo "    ConnectTimeout 5"
      echo "    RequestTTY no"
    done
    echo "$END"
  }
}

case "${1:-}" in
  --verify)
    rc=0
    if [[ -f "$KEY" ]]; then
      perm="$(stat -c '%a' "$KEY" 2>/dev/null || echo 000)"
      fp="$(ssh-keygen -lf "$KEY.pub" 2>/dev/null | awk '{print $2}')"
      echo "KEY      $KEY (${fp:-fingerprint unavailable}, mode $perm)"
      [[ "$perm" == "600" || "$perm" == "400" ]] || { echo "         DEGRADED: expected mode 600"; rc=2; }
    else
      echo "KEY      ABSENT"; rc=1
    fi
    if grep -qF "$BEGIN" "$CONFIG" 2>/dev/null; then
      echo "CONFIG   present in $CONFIG"
      for row in "${TARGETS[@]}"; do
        read -r target addr <<<"$row"
        grep -qF "Host $target $addr" "$CONFIG" || { echo "         MISSING target $target"; rc=2; }
      done
    else
      echo "CONFIG   ABSENT"; rc=1
    fi
    exit $rc ;;
  --print)
    [[ -f "$KEY.pub" ]] || die "no key yet; run without arguments first"
    cat "$KEY.pub"; exit 0 ;;
  --remove)
    rm -f "$KEY" "$KEY.pub"
    if [[ -f "$CONFIG" ]]; then
      tmp="$(mktemp)"
      awk -v b="$BEGIN" -v e="$END" '
        $0 == b { skip = 1 } skip != 1 { print } $0 == e { skip = 0 }' "$CONFIG" > "$tmp"
      cat "$tmp" > "$CONFIG" && rm -f "$tmp"
      chmod 600 "$CONFIG"
    fi
    echo "Removed the outbound bounded-recovery identity from $HOST_ID."
    echo "Revoke the matching authorized_keys entry on each E2 as well:"
    echo "  install-bounded-recovery-identity.sh --remove"
    exit 0 ;;
esac

# --- Generate, once ------------------------------------------------------------------
command -v ssh-keygen >/dev/null 2>&1 \
  || die "ssh-keygen is not installed; cannot generate the bounded-recovery keypair"

if [[ -f "$KEY" ]]; then
  echo "Reusing the existing bounded-recovery key at $KEY."
  echo "To rotate it, run --remove here, --remove on each E2, then re-run this."
else
  # A dedicated key, never an existing one. Section 5.4 rule 1: reusing a key makes the
  # mesh symmetric by accident, and an accident is exactly how that happens.
  ssh-keygen -q -t ed25519 -N '' -C "dial-bounded-recovery@$HOST_ID" -f "$KEY" \
    || die "could not generate the keypair"
  echo "Generated a dedicated bounded-recovery keypair."
fi
chmod 600 "$KEY"; chmod 644 "$KEY.pub"

# Refuse to continue if this key is also an authorized key here. That would mean the same
# identity opens both directions, which is the one property this design must not have.
if [[ -f "$SSH_DIR/authorized_keys" ]] \
   && grep -qF "$(awk '{print $2}' "$KEY.pub")" "$SSH_DIR/authorized_keys" 2>/dev/null; then
  die "this key is also in $SSH_DIR/authorized_keys on $HOST_ID.
That would make the recovery mesh symmetric. Remove it there, or --remove and re-run."
fi

# --- Wire SSH ------------------------------------------------------------------------
touch "$CONFIG"; chmod 600 "$CONFIG"
tmp="$(mktemp)"
awk -v b="$BEGIN" -v e="$END" '
  $0 == b { skip = 1 } skip != 1 { print } $0 == e { skip = 0 }' "$CONFIG" > "$tmp"
config_block >> "$tmp"
cat "$tmp" > "$CONFIG" && rm -f "$tmp"
chmod 600 "$CONFIG"

# Seed known_hosts now: StrictHostKeyChecking=yes means an unseeded target fails closed,
# and discovering that during an outage is discovering it too late.
if [[ -x "$FABRIC_DIR/seed-known-hosts.sh" ]]; then
  bash "$FABRIC_DIR/seed-known-hosts.sh" || true
fi

cat <<EOF

Outbound bounded-recovery identity ready on $HOST_ID.

  key           : $KEY (private half stays here — never copy it anywhere)
  fingerprint   : $(ssh-keygen -lf "$KEY.pub" | awk '{print $2}')
  targets       : $(printf '%s ' "${TARGETS[@]%% *}")
  capability    : R0 observe + R1 restart of each target's own recovery units

NEXT — on each E2, as the owner, with this public key:

$(cat "$KEY.pub")

  install-bounded-recovery-identity.sh /path/to/that.pub
  install-bounded-recovery-identity.sh --verify

THEN — back here, prove it end to end:

  verify-two-way-recovery.sh
EOF
