import { test, expect } from 'vitest';import path from 'node:path';import { fileURLToPath } from 'node:url';
import { buildFrontendProductExperienceProjection, buildSurfaceStateMatrix, buildSurfaceManifest, resolveProductDesignProfile } from '../agent-system/orchestration/frontend-product-experience.mjs';
import { normalizeDesignCandidate } from '../agent-system/orchestration/frontend-design-normalizer.mjs';
import { areVisualEnvelopesComparable, evaluateFrontendCertification, evaluateDesignCodeParity, evaluateDesignLint, measureDesignSystemSaturation, VISUAL_GATES } from '../agent-system/orchestration/frontend-certification.mjs';
import { classifyTask } from '../agent-system/orchestration/task-triage.mjs';
import { providerPromptFromDesignBrief, createFigmaCandidateState } from '../agent-system/orchestration/frontend-design-provider-orchestrator.mjs';
import { compileFrontendTokens } from '../agent-system/orchestration/frontend-token-compiler.mjs';
import { buildComponentLabFixtures } from '../agent-system/orchestration/frontend-component-lab.mjs';
import { attributeFrontendOutcome } from '../agent-system/orchestration/frontend-evaluation.mjs';
import { compileFrontendLearningSignal } from '../agent-system/orchestration/frontend-learning.mjs';

const here=path.dirname(fileURLToPath(import.meta.url));const repoDir=path.resolve(here,'..');
const unit={unit_lineage_id:'DU-TEST',unit_revision_hash:'rev1',feature_ids:['SPARE-F001'],knowledge_route_ids:['PRODUCT_EXPERIENCE'],design_authorities:[{id:'POS-BENCHMARK',ref:'benchmarks/pos.png',authority_level:'CANONICAL_REFERENCE',required_fidelity:'PIXEL_INTENT'}]};
const feature={feature_id:'SPARE-F001',module:'SPARE CATALOG',outcome:'high quality parts browser'};
const contract={feature_id:'SPARE-F001',surfaces:[{surface_id:'catalog',route:'/catalog',required_states:['READY','LOADING','EMPTY','ERROR'],user_journey_refs:['JOURNEY-BUY-PART']}],acceptance_contract:['functional'],security_profile:'standard'};

test('product profile inheritance resolves DIAL family overlay deterministically',()=>{const p=resolveProductDesignProfile({repoDir,unit,featureRecord:feature});expect(p.artifact_id).toBe('dial.spare');expect(p.profile.pattern_allowlist).toContain('PREMIUM_AUTOMOTIVE');const again=resolveProductDesignProfile({repoDir,unit,featureRecord:feature});expect(p.content_hash).toBe(again.content_hash);});

test('surface state matrix prevents happy-path-only frontend contracts',()=>{const m=buildSurfaceManifest({unit,featureRecord:feature,contractRecord:contract});const states=buildSurfaceStateMatrix({surfaceManifest:m,contractRecord:contract});const ids=states.surfaces[0].states.map((x)=>x.state_id);for(const id of ['READY','LOADING','EMPTY','ERROR','OFFLINE','STALE','PERMISSION_DENIED','DEGRADED'])expect(ids).toContain(id);});

test('frontend projection compiles profile, manifest, visual authority, presentation decision and VRDE',()=>{const p=buildFrontendProductExperienceProjection({repoDir,unit,featureRecord:feature,contractRecord:contract,instruction:'Reconstruct the catalog screen exactly from benchmark',affectedPaths:['apps/android/CatalogScreen.kt']});expect(p.applicable).toBe(true);expect(p.presentation_decision.execution_mode).toBe('RECONSTRUCT');expect(p.presentation_decision.renderer_id).toBe('JETPACK_COMPOSE');expect(p.visual_reference_spec.references[0].authority_level).toBe('CANONICAL_REFERENCE');expect(p.visual_render_determinism_envelope.content_hash).toMatch(/^[0-9a-f]{64}$/);});

test('normalizer fails closed on unapproved design vocabulary and passes approved registry vocabulary',()=>{const fdep={applicable:true,task_id:'t1',content_hash:'fdep1',change_budget:{allowed_structural_delta:'MINIMUM_NECESSARY',new_token_ids:[],new_component_ids:[],new_pattern_ids:[],approved_visual_delta_refs:[],content_hash:'b1'}};const bad=normalizeDesignCandidate({repoDir,fdep,candidate:{token_ids:['invented.space'],component_ids:['dial.surface.card'],pattern_ids:['PRECISION_MINIMALISM']}});expect(bad.status).toBe('REJECTED');expect(bad.violations.some((x)=>x.startsWith('UNAPPROVED_TOKEN:'))).toBe(true);const good=normalizeDesignCandidate({repoDir,fdep,candidate:{token_ids:['semantic.surface.gap'],component_ids:['dial.surface.card'],pattern_ids:['PRECISION_MINIMALISM']}});expect(good.status).toBe('NORMALIZED');});

test('visual evidence is comparable only under the same render determinism envelope',()=>{const a={platform:'WEB',renderer:'REACT_TYPESCRIPT',viewport:{width:100,height:100},density:'STANDARD',locale:'en',timezone:'UTC',color_scheme:'LIGHT',font_scale:1,animation_policy:'OFF',capture_settle_policy:'IDLE',dynamic_region_policy:'MASK_DECLARED_ONLY',asset_manifest_hash:'a',framework_version:'1',harness_version:'1'};expect(areVisualEnvelopesComparable(a,{...a}).comparable).toBe(true);expect(areVisualEnvelopesComparable(a,{...a,font_scale:1.1}).comparable).toBe(false);});

test('canonical reference V8 cannot be cleared without authority signoff',()=>{const fdep={task_id:'t2',content_hash:'f2',visual_reference_spec:{references:[{authority_level:'CANONICAL_REFERENCE'}]},visual_render_determinism_envelope:{platform:'WEB',renderer:'REACT_TYPESCRIPT',viewport:{},density:'STANDARD',locale:'en',timezone:'UTC',color_scheme:'LIGHT',font_scale:1,animation_policy:'OFF',capture_settle_policy:'IDLE',dynamic_region_policy:'MASK_DECLARED_ONLY',asset_manifest_hash:null,framework_version:null,harness_version:null}};const hard=Object.fromEntries(['NO_FAKE_DATA','NO_PLACEHOLDER_HELPER_TEXT','NO_DEAD_CONTROLS','REQUIRED_STATES_PRESENT','SCREEN_MAPPED_TO_AUTHORITY','ACTIONS_HAVE_DOMAIN_CONTRACT','DONOR_TRANSFORMED','ACCESSIBILITY_SEMANTICS','RESPONSIVE_BEHAVIOR','NO_FAKE_IMPLEMENTATION_AFFORDANCES','FRC_SURFACE_COMPLETE'].map((x)=>[x,true]));const visual=Object.fromEntries(VISUAL_GATES.map((x)=>[x,true]));visual.V8_AUTHORITY_SIGNOFF=false;const result=evaluateFrontendCertification({repoDir,fdep,evidence:{product_experience_hard:hard,product_experience_qualitative:{project_rubric_passed:true,oracle_evidence_hash:'oracle'},visual,surface_state_matrix_coverage:true,accessibility_passed:true,performance_passed:true,security_passed:true,domain_truth_passed:true,design_normalization:{status:'NORMALIZED'},design_lint:{status:'PASSED'},design_code_parity:{status:'ALIGNED'},render_vrde:{...fdep.visual_render_determinism_envelope}}});expect(result.ok).toBe(false);expect(result.failures).toContain('V8_AUTHORITY_SIGNOFF');});

test('generic triage remains primary while frontend routing is second-stage',()=>{const px=buildFrontendProductExperienceProjection({repoDir,unit,featureRecord:feature,contractRecord:contract,instruction:'design catalog ui',affectedPaths:['CatalogScreen.kt']});const unitMap={unit_revision_hash:'rev1',product_experience_map:{applicable:true,frontend_projection:px}};const t=classifyTask({unitMap,instruction:'design frontend screen',affectedPaths:['CatalogScreen.kt']});expect(t.archetype).toBe('NEW_FRONTEND_DESIGN');expect(t.frontend_routing.applicable).toBe(true);expect(t.mandatory_gates).toContain('FDEP_CURRENT');expect(t.policy_version).toBe('dial-aef-triage-1');});

test('provider brief is bounded and Figma promotion is an explicit authority transition',()=>{const px=buildFrontendProductExperienceProjection({repoDir,unit,featureRecord:feature,contractRecord:contract,instruction:'design ui'});const fdep={task_id:'t3',content_hash:'f3',surface_manifest:px.surface_manifest,surface_state_matrix:px.surface_state_matrix,presentation_decision:px.presentation_decision,visual_reference_spec:px.visual_reference_spec};const brief={content_hash:'brief3'};const prompt=providerPromptFromDesignBrief({brief,fdep});expect(prompt).toMatch(/non-authoritative candidate/i);const c=createFigmaCandidateState({taskId:'t3',fileRef:'figma:file',fdep,action:'CREATE_CANDIDATE'});expect(c.authority_state).toBe('NON_AUTHORITATIVE_CANDIDATE');expect(()=>createFigmaCandidateState({taskId:'t3',fileRef:'figma:file',fdep,previous:c,action:'PROMOTE'})).toThrow(/PROMOTION_REQUIRES_PENDING/);const pending=createFigmaCandidateState({taskId:'t3',fileRef:'figma:file',fdep,previous:c,action:'REQUEST_PROMOTION'});expect(()=>createFigmaCandidateState({taskId:'t3',fileRef:'figma:file',fdep,previous:pending,action:'PROMOTE'})).toThrow(/AUTHORITY_APPROVAL/);const promoted=createFigmaCandidateState({taskId:'t3',fileRef:'figma:file',fdep,previous:pending,action:'PROMOTE',authorityApprovalRef:'owner:approved'});expect(promoted.authority_state).toBe('PROMOTED_VISUAL_AUTHORITY');});

test('DTCG compiler and component lab produce deterministic target artifacts',()=>{const css=compileFrontendTokens({repoDir,target:'CSS'});expect(css.output).toMatch(/--semantic-surface-gap: 16px/);const lab=buildComponentLabFixtures({repoDir,componentIds:['dial.state.panel']});expect(lab.fixtures.some((x)=>x.state==='OFFLINE')).toBe(true);});

test('parity, lint and saturation support composite verification',()=>{expect(evaluateDesignCodeParity({design:{component_ids:['a']},code:{component_ids:['a']}}).status).toBe('ALIGNED');expect(evaluateDesignLint({repoDir,implementation:{token_ids:['semantic.surface.gap'],component_ids:['dial.surface.card']}}).status).toBe('PASSED');expect(measureDesignSystemSaturation({implementation:{total_visual_elements:100,governed_visual_elements:97}}).state).toBe('GREEN');});

test('learning is cause-attributed and cannot rewrite canon',()=>{const cert={ok:false,content_hash:'cert',failures:['V2_GEOMETRY']};const attr=attributeFrontendOutcome({certification:cert,resourceDiagnostics:{missing_required_context:true}});expect(attr.cause).toBe('RESOURCE_DEFICIT');const signal=compileFrontendLearningSignal({taskId:'t4',fdep:{content_hash:'f4'},certification:cert,outcomeAttribution:attr});expect(signal.resource_improvement_required).toBe(true);expect(signal.authority_constraints.project_truth_mutation).toBe(false);});
