import { describe,it,expect } from 'vitest';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { classifyTask } from '../agent-system/orchestration/task-triage.mjs';import { selectExecutionTopology } from '../agent-system/orchestration/execution-topology.mjs';import { hardEligibility,selectHcxWorkers } from '../agent-system/orchestration/harness-capability-exchange.mjs';import { issueWorktreeLease,assertWorktreeLease,closeWorktreeLease } from '../agent-system/orchestration/worker-lease-manager.mjs';import { reserveCompute,settleCompute } from '../agent-system/orchestration/compute-governor.mjs';import { sanitizeAndClassifyProviderInput } from '../agent-system/orchestration/donor-egress-guard.mjs';import { quarantineDesignArtifact,buildDesignCandidateManifest,admitDesignCandidate } from '../agent-system/orchestration/design-candidate-admission.mjs';import { buildDevelopmentExecutionReceipt } from '../agent-system/orchestration/execution-receipt.mjs';import { checkAdaptiveExecutionArchitecture } from '../agent-system/orchestration/adaptive-execution-architecture-check.mjs';
import { resolvePacketEngineeringKnowledge } from '../agent-system/orchestration/engineering-knowledge-broker.mjs';import { planAdaptiveExecution } from '../agent-system/orchestration/adaptive-execution-planner.mjs';import { supersedeActiveExecutionTasks } from '../agent-system/orchestration/task-execution-envelope.mjs';import { writeJsonAtomic,readJson } from '../agent-system/orchestration/state-store.mjs';
const worker=(id='w',quality=0)=>({harness_id:id,authority_class:'EXECUTION_WORKER',manager_runtime_eligible:false,qualification:{state:'QUALIFIED'},operational:{health_state:'HEALTHY',quota_state:'NORMAL'},safety:{allowed_risk_classes:['LOW','MEDIUM','HIGH','CRITICAL'],allowed_data_classes:['INTERNAL_SAFE_FOR_APPROVED_PROVIDER']},capabilities:{coding:true,visualReasoning:true},allowed_roles:['BUILDER','FRONTEND_BUILDER'],identity:{worker_identity_hash:id},performance:{sample_count:10,final_accept_count:quality,first_pass_accept_count:quality,escaped_defect_rate:0,median_rework_ratio:0,p95_latency_ms:10,median_total_tokens:100}});
describe('DIAL Adaptive Execution Fabric Rev2',()=>{
 it('keeps critical architecture work competitive before parallelism',()=>{const t=classifyTask({instruction:'change project truth architecture',affectedPaths:['a','b']});t.parallelizable_dimensions=[{allowed_write_paths:['a']},{allowed_write_paths:['b']}];expect(selectExecutionTopology({triage:t,budget:{max_concurrent_workers:2,max_frontier_invocations:2},policy:{}}).topology).toBe('COMPETITIVE_CELL');});
 it('blocks required topology rather than budget-downgrading',()=>{const t={risk_class:'CRITICAL',archetype:'ARCHITECTURE_CHANGE',mandatory_competitive_review:true};expect(selectExecutionTopology({triage:t,budget:{max_concurrent_workers:1},policy:{}}).reason).toBe('BUDGET_BLOCKED_REQUIRED_TOPOLOGY');});
 it('HCX structurally rejects manager runtime cards',()=>{const m={...worker(),authority_class:'MANAGER_RUNTIME',manager_runtime_eligible:true};expect(hardEligibility(m,{triage:{risk_class:'LOW',required_capabilities:['coding']},role:'BUILDER'}).ok).toBe(false);});
 it('hard filtering occurs before empirical route selection',()=>{const bad={...worker('bad',10),operational:{health_state:'UNKNOWN',quota_state:'NORMAL'}};const good=worker('good',8);const r=selectHcxWorkers({cards:[bad,good],triage:{risk_class:'LOW',required_capabilities:['coding'],triage_result_hash:'x'},role:'BUILDER'});expect(r.selected_workers[0].identity.worker_identity_hash).toBe('good');expect(r.excluded_candidates[0].reason_codes).toContain('NOT_HEALTHY');});
 it('prevents cross-task overlapping write leases',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'aef-'));const a=issueWorktreeLease({root,taskId:'a',workerId:'1',writePaths:['packages/payments/**']});const b=issueWorktreeLease({root,taskId:'b',workerId:'2',writePaths:['packages/payments/src/**']});expect(a.ok).toBe(true);expect(b.reason).toBe('WRITE_LEASE_CONFLICT');fs.rmSync(root,{recursive:true,force:true});});
 it('rejects revoked fencing at write/integration boundary',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'aef-'));const a=issueWorktreeLease({root,taskId:'a',workerId:'1',writePaths:['packages/x/**']}).lease;closeWorktreeLease({root,leaseId:a.lease_id,state:'REVOKED'});expect(()=>assertWorktreeLease({root,leaseId:a.lease_id,workerId:'1',fencingToken:a.fencing_token,path:'packages/x/a.ts'})).toThrow();fs.rmSync(root,{recursive:true,force:true});});
 it('reserves and settles compute transactionally',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'aef-'));const r=reserveCompute({root,taskId:'a',budget:{max_concurrent_workers:1,max_input_tokens_total:100,max_output_tokens_total:100},estimatedInputTokens:20,estimatedOutputTokens:10});expect(r.ok).toBe(true);expect(settleCompute({root,reservationId:r.reservation.reservation_id,actualInputTokens:12,actualOutputTokens:4}).state).toBe('SETTLED');fs.rmSync(root,{recursive:true,force:true});});
 it('denies restricted provider egress and redacts secrets',()=>{const r=sanitizeAndClassifyProviderInput('customer email is x@y.com token=abcdefghijklmnop');expect(r.ok).toBe(false);expect(r.findings).toContain('SECRET_REDACTED');});
 it('quarantines executable provider output',()=>{expect(quarantineDesignArtifact({content:'<script>alert(1)</script>'}).ok).toBe(false);});
 it('admits only quarantined-safe conforming design candidates',()=>{const q=quarantineDesignArtifact({content:'<main>Safe</main>'});const c=buildDesignCandidateManifest({taskId:'t',providerId:'stitch',unitLineageId:'u',unitRevisionHash:'r',designAuthorityProjectionHash:'d',rawContent:'<main>Safe</main>',quarantine:q});expect(admitDesignCandidate({candidate:c,authorityConforms:true,requiredStatesPresent:true}).ok).toBe(true);});
 it('refuses secrets in execution receipts',()=>{expect(()=>buildDevelopmentExecutionReceipt({task:{note:'api_key=abcdefghijklmnop'}})).toThrow('RECEIPT_SECRET_DETECTED');});
 it('keeps the additive architecture matrix green',()=>{const r=checkAdaptiveExecutionArchitecture();expect(r.status).toBe('GREEN');expect(r.passed).toBe(25);});

 it('owner-steer supersession revokes active task leases',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'aef-'));const l=issueWorktreeLease({root,taskId:'steer',workerId:'w',writePaths:['packages/x/**']}).lease;writeJsonAtomic('execution/tasks/steer/envelope.json',{task_id:'steer',envelope_hash:'e',state:'RUNNING'},root);const out=supersedeActiveExecutionTasks({root,reason:'OWNER_STEER:test'});expect(out.map(x=>x.task_id)).toContain('steer');expect(readJson('execution/tasks/steer/envelope.json',null,root).state).toBe('SUPERSEDED');expect(()=>assertWorktreeLease({root,leaseId:l.lease_id,workerId:'w',fencingToken:l.fencing_token,path:'packages/x/a.ts'})).toThrow();fs.rmSync(root,{recursive:true,force:true});});
 it('plans a real Unit-scoped VEKL packet through HCX',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'aef-real-'));const repo=process.cwd(),packet='aefreal001';const m=resolvePacketEngineeringKnowledge({repoDir:repo,root,packetId:packet,instruction:'Implement bounded PLAT-F014 pricing test repair',metadata:{feature_id:'PLAT-F014',affected_paths:['packages/round-credit/src/credit-model.ts'],available_tools:[]}});writeJsonAtomic('state/runtime-health.json',{schema_version:2,runtimes:{codex_app_server:{state:'HEALTHY',requested_model:'gpt-5.6-sol',resolved_model:'gpt-5.6-sol',observed_at:new Date().toISOString(),details:{toolchain_usable:true}},claude_code:{state:'HEALTHY',requested_model:'claude-sonnet-5',resolved_model:'claude-sonnet-5',observed_at:new Date().toISOString(),details:{toolchain_usable:true}}},updated_at:new Date().toISOString()},root);const plan=planAdaptiveExecution({repoDir:repo,root,packetId:packet,instruction:'Implement bounded PLAT-F014 pricing test repair',budgetClass:'S',allowedPaths:['packages/round-credit/src/credit-model.ts']});expect(m.knowledge_context.scope).toBe('DEVELOPMENT_UNIT');expect(plan.envelope_hash).toMatch(/^[0-9a-f]{64}$/);expect(plan.routing.selected_workers.length).toBeGreaterThan(0);expect(plan.topology).toBe('SOLO');fs.rmSync(root,{recursive:true,force:true});},60000);

});
