import { test, expect } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSourceManifest } from '../agent-system/orchestration/structural-source-manifest.mjs';
import { classifyShellEffect, networkAccessIntent, networkPolicyDecision } from '../agent-system/orchestration/shell-effect-classifier.mjs';
import { TypeScriptStructuralCodeGraphProvider, GraphifyStructuralCodeGraphProvider, normalizeStructuralGraph } from '../agent-system/orchestration/structural-code-graph-provider.mjs';
import { publishStructuralSnapshot, loadCurrentStructuralSnapshot, structuralFingerprintForUnit, boundedStructuralTraversal, compareExpectedObservedDelta, evaluateStructuralContracts, buildImpactEnvelope, structuralMergeConflictRisk, createStructuralReplayBundle, verifyStructuralReplayBundle, deterministicRebuildCertification, resolveStructuralReality, checkStructuralBinding, createOrphanBaseline, evaluateOrphanBaseline, reserveStructuralCompute, settleStructuralCompute, bindStructuralIntegrationEvidence } from '../agent-system/orchestration/structural-reality.mjs';
import { checkStructuralArchitecture } from '../agent-system/orchestration/structural-architecture-check.mjs';

const here=path.dirname(fileURLToPath(import.meta.url));const repoDir=path.resolve(here,'..');
function tempRepo(){const r=fs.mkdtempSync(path.join(os.tmpdir(),'dial-struct-'));fs.mkdirSync(path.join(r,'src'),{recursive:true});fs.mkdirSync(path.join(r,'tests'),{recursive:true});fs.mkdirSync(path.join(r,'agent-system/registries'),{recursive:true});fs.writeFileSync(path.join(r,'src/a.ts'),"import { b } from './b';\nexport function a(){ return b(); }\n");fs.writeFileSync(path.join(r,'src/b.ts'),"export function b(){ return 1; }\n");fs.writeFileSync(path.join(r,'tests/a.test.ts'),"import { a } from '../src/a';\na();\n");fs.copyFileSync(path.join(repoDir,'agent-system/registries/STRUCTURAL_REALITY_POLICY.json'),path.join(r,'agent-system/registries/STRUCTURAL_REALITY_POLICY.json'));fs.writeFileSync(path.join(r,'agent-system/registries/DEVELOPMENT_UNIT_REGISTRY.json'),JSON.stringify({units:[{unit_lineage_id:'unit:a',unit_revision_hash:'rev-a',feature_ids:['F-A'],affected_paths:['src/**'],knowledge_route_ids:[]}]}));return r;}
function manifest(r){return buildSourceManifest({repoDir:r,declarations:['src/**'],policy:{profile:'DIAL_CODE_ONLY_V1'}});}

test('directory declaration hash contains recursive membership but not prefix siblings',()=>{const r=tempRepo();fs.mkdirSync(path.join(r,'src2'));fs.writeFileSync(path.join(r,'src2/x.ts'),'x');const m=manifest(r);expect(m.entries.map(x=>x.path)).toEqual(['src/a.ts','src/b.ts']);});
test('membership and bytes are identity bearing',()=>{const r=tempRepo();const a=manifest(r).source_manifest_hash;fs.writeFileSync(path.join(r,'src/c.ts'),'export const c=1;');const b=manifest(r).source_manifest_hash;expect(b).not.toBe(a);fs.writeFileSync(path.join(r,'src/a.ts'),'changed');expect(manifest(r).source_manifest_hash).not.toBe(b);});
test('overlapping declarations preserve owners without double counting',()=>{const r=tempRepo();const m=buildSourceManifest({repoDir:r,declarations:['src/**','src/a.ts'],owners:{'src/**':['U1'],'src/a.ts':['U2']}});const a=m.entries.find(x=>x.path==='src/a.ts');expect(a.owners).toEqual(['U1','U2']);expect(m.entries.filter(x=>x.path==='src/a.ts')).toHaveLength(1);});
test('symlinks are hashed as links and not followed',()=>{const r=tempRepo();const outside=path.join(os.tmpdir(),`outside-${Date.now()}.txt`);fs.writeFileSync(outside,'secret');try{fs.symlinkSync(outside,path.join(r,'src/link'));const m=manifest(r);expect(m.entries.find(x=>x.path==='src/link')?.kind).toBe('SYMLINK');}catch(e){if(e.code!=='EPERM')throw e;}});
test('path escape fails closed',()=>{const r=tempRepo();expect(()=>buildSourceManifest({repoDir:r,declarations:['../escape']})).toThrow(/escapes repository/);});

test('safe status and rg inspection remain read-only',()=>{expect(classifyShellEffect('git status --short').effect).toBe('READ_ONLY');expect(classifyShellEffect('rg TODO src').effect).toBe('READ_ONLY');});
test('git branch creation is material while listing is read-only',()=>{expect(classifyShellEffect('git branch --list').effect).toBe('READ_ONLY');expect(classifyShellEffect('git branch feature/x').effect).toBe('MATERIAL');});
test('shell composition cannot smuggle a mutator',()=>{for(const c of ['git status && rm x','rg foo | xargs rm','cat x > y','echo $(rm x)','find . -delete'])expect(classifyShellEffect(c).effect).toBe('MATERIAL');});
test('explicit packet re-resolution remains non-material',()=>{expect(classifyShellEffect('node agent-system/bin/engineering-knowledge-resolve.mjs --packet-id p1').effect).toBe('EXPLICIT_RERESOLUTION');});
test('network intent extracts deterministic targets',()=>{expect(networkAccessIntent('Bash',{command:'curl -fsS https://api.example.com/v1/health'})).toMatchObject({network:true,targets:['api.example.com']});expect(networkAccessIntent('web_search',{query:'dial'}).network).toBe(true);});
test('task network policy is fail closed and host allowlist bounded',()=>{expect(networkPolicyDecision({toolName:'Bash',toolInput:{command:'curl https://api.example.com/x'},allowlist:[]}).reason).toBe('NETWORK_ACCESS_NOT_GRANTED');expect(networkPolicyDecision({toolName:'Bash',toolInput:{command:'curl https://api.example.com/x'},allowlist:['api.example.com']}).ok).toBe(true);expect(networkPolicyDecision({toolName:'Bash',toolInput:{command:'curl https://evil.example/x'},allowlist:['api.example.com']}).reason).toBe('NETWORK_TARGET_NOT_ALLOWED');expect(networkPolicyDecision({toolName:'web_search',toolInput:{query:'dial'},allowlist:['google.com']}).reason).toBe('NETWORK_TARGET_UNRESOLVED');});

test('typescript provider build is deterministic for identical bytes',()=>{const r=tempRepo(),p=new TypeScriptStructuralCodeGraphProvider();const a=p.build({repoDir:r,repoSha:'abc',declarations:['src/**/*.ts']});const b=p.build({repoDir:r,repoSha:'abc',declarations:['src/**/*.ts']});expect(a.normalized_graph_hash).toBe(b.normalized_graph_hash);expect(a.provider_graph_hash).toBe(b.provider_graph_hash);});
test('normalizer creates provider-independent structural identities and drops external nodes',()=>{const g=normalizeStructuralGraph({provider:'graphify',providerVersion:'0.9.58',repository:'x/y',nodes:[{id:'1',path:'src/a.ts',kind:'FUNCTION',name:'a'},{id:'2',path:'../escape',kind:'FUNCTION',name:'bad'}],edges:[]});expect(g.nodes).toHaveLength(1);expect(g.nodes[0].structural_id).toMatch(/^sym:[0-9a-f]{64}$/);});
test('inferred provider relation stays low authority and review required',()=>{const g=normalizeStructuralGraph({provider:'graphify',providerVersion:'0.9.58',repository:'x/y',nodes:[{id:'1',path:'src/a.ts',kind:'FUNCTION',name:'a'},{id:'2',path:'src/b.ts',kind:'FUNCTION',name:'b'}],edges:[{source:'1',target:'2',inferred:true}]});expect(g.edges[0].relationship).toBe('GRAPHIFY_INFERRED_LINK');expect(g.edges[0].review_required).toBe(true);expect(g.edges[0].authority).toBe('MODEL_INFERRED');});
test('Graphify provider refuses execution until exact qualification',async()=>{const r=tempRepo(),p=new GraphifyStructuralCodeGraphProvider();await expect(p.build({repoDir:r,rawGraph:{nodes:[],edges:[]},qualification:{version:'0.9.58'}})).rejects.toThrow(/GRAPHIFY_NOT_QUALIFIED/);});
test('Graphify provider accepts exact fail-closed qualification evidence',async()=>{const r=tempRepo(),p=new GraphifyStructuralCodeGraphProvider();const q={version:'0.9.58',no_egress_proven:true,source_tree_immutable_proven:true,parser_versions_hash:'p',schema_sample_hash:'s'};const x=await p.build({repoDir:r,repoSha:'abc',rawGraph:{nodes:[{id:'1',path:'src/a.ts',kind:'MODULE',name:'src/a.ts'}],edges:[]},qualification:q});expect(x.provider).toBe('graphify');});

test('generation publication is atomic and reusable',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'dial-control-'));const snap={schema_version:'dial.structural-graph.v1',provider:'typescript-structural',provider_version:'dial-1',repo_sha:'abc',source_file_manifest_hash:'s',normalized_graph_hash:'n',nodes:[],edges:[],extraction_profile:'DIAL_CODE_ONLY_V1'};const a=publishStructuralSnapshot({root,snapshot:snap});const b=loadCurrentStructuralSnapshot(root);expect(b.snapshot_hash).toBe(a.snapshot_hash);});
test('unit structural fingerprint is separate from canonical unit revision',()=>{const r=tempRepo(),p=new TypeScriptStructuralCodeGraphProvider(),snap=p.build({repoDir:r,repoSha:'abc',declarations:['src/**/*.ts']}),m=manifest(r);const f=structuralFingerprintForUnit({snapshot:snap,manifest:m});expect(f.unit_structural_fingerprint).toMatch(/^[0-9a-f]{64}$/);expect(f.unit_structural_fingerprint).not.toBe('rev-a');});
test('bounded traversal structurally gates before semantic rerank',()=>{const r=tempRepo(),p=new TypeScriptStructuralCodeGraphProvider(),snap=p.build({repoDir:r,repoSha:'abc',declarations:['src/**/*.ts']}),m=buildSourceManifest({repoDir:r,declarations:['src/a.ts']});const t=boundedStructuralTraversal({snapshot:snap,manifest:m,query:'b',weights:{IMPORTS:.7,CONTAINS:.8},maxHops:2,maxNodes:20});expect(t.seed_nodes.length).toBeGreaterThan(0);expect(t.visited_nodes.length).toBeGreaterThanOrEqual(t.seed_nodes.length);});
test('expected versus observed graph delta fails on undeclared divergence',()=>{const before={edges:[{edge_ref:'a'}]},after={edges:[{edge_ref:'a'},{edge_ref:'b'}]};expect(compareExpectedObservedDelta({before,after,expected:{add_edges:[]}}).state).toBe('STRUCTURAL_DELTA_MISMATCH');});
test('impact envelope exposes incoming blast radius',()=>{const s={nodes:[{node_ref:'a',source_path:'src/a.ts'},{node_ref:'b',source_path:'src/b.ts'}],edges:[{source_ref:'b',target_ref:'a'}]};const i=buildImpactEnvelope({snapshot:s,changedPaths:['src/a.ts']});expect(i.impacted_nodes).toContain('b');});
test('merge conflict risk is advisory',()=>{const r=structuralMergeConflictRisk({leftNodes:['a','b'],rightNodes:['b','c']});expect(r.advisory_only).toBe(true);expect(r.state).not.toBe('NONE');});
test('structural contracts are policy driven',()=>{const p=JSON.parse(fs.readFileSync(path.join(repoDir,'agent-system/registries/STRUCTURAL_REALITY_POLICY.json'),'utf8'));const f=evaluateStructuralContracts({snapshot:{nodes:[],edges:[]},policy:p});expect(f).toHaveLength(5);expect(f.map(x=>x.contract_id)).toEqual(['SC-001','SC-002','SC-003','SC-004','SC-005']);});
test('replay bundle detects tampering',()=>{const u={unit_lineage_id:'u',unit_revision_hash:'r',map_hash:'m',structural_reality_map:{map_hash:'s',snapshot_hash:'x',source_manifest_hash:'y',unit_structural_fingerprint:'z',frontend_projection_hash:'f'}};const b=createStructuralReplayBundle({unitMap:u,traceHash:'t'});expect(verifyStructuralReplayBundle(b).ok).toBe(true);expect(verifyStructuralReplayBundle({...b,snapshot_hash:'tampered'}).ok).toBe(false);});
test('deterministic certification requires identical structural identities',()=>{expect(deterministicRebuildCertification({first:{provider:'p',provider_version:'1',repo_sha:'a',source_file_manifest_hash:'s',normalized_graph_hash:'n'},second:{provider:'p',provider_version:'1',repo_sha:'a',source_file_manifest_hash:'s',normalized_graph_hash:'n'}}).ok).toBe(true);});
test('missing structural snapshot is advisory in shadow rollout',()=>{const r=tempRepo(),root=fs.mkdtempSync(path.join(os.tmpdir(),'dial-control-')),unit={unit_lineage_id:'unit:a',unit_revision_hash:'rev-a',feature_ids:['F-A'],affected_paths:['src/**']};const x=resolveStructuralReality({repoDir:r,root,unit,frontendProjection:{projection_hash:'px'}});expect(x.state).toBe('MISSING_ADVISORY');expect(x.frontend_projection_hash).toBe('px');});
test('bound structural source and frontend projection drift fail closed',()=>{const r=tempRepo();const unitMap={structural_reality_map:{source_manifest_hash:'new',unit_structural_fingerprint:'new-fp',state:'CURRENT'},product_experience_map:{frontend_projection:{projection_hash:'new-px'}}};const c=checkStructuralBinding({repoDir:r,root:fs.mkdtempSync(path.join(os.tmpdir(),'dial-control-')),unitMap,binding:{source_manifest_hash:'old',unit_structural_fingerprint:'old-fp',frontend_projection_hash:'old-px'}});expect(c.ok).toBe(false);expect(c.reasons).toContain('FRONTEND_PROJECTION_CHANGED');});

test('orphan baseline never amnesties protected or changed orphan evidence',()=>{const rec={orphans:[{node_ref:'p',source_path:'packages/payment/orphan.ts'},{node_ref:'x',source_path:'packages/misc/orphan.ts'}]};const b=createOrphanBaseline({reconciliation:rec,protectedDomains:['PAYMENT']});const e=evaluateOrphanBaseline({reconciliation:rec,baseline:b,changedPaths:['packages/misc/orphan.ts'],protectedDomains:['PAYMENT']});expect(e.ok).toBe(false);expect(e.unamnestied.map(x=>x.reason).sort()).toEqual(['CHANGED_ORPHAN','PROTECTED_DOMAIN_NO_AMNESTY']);});
test('structural compute reservation settles actuals without waiving review',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'dial-control-'));const r=reserveStructuralCompute({root,taskId:'t',estimatedNodes:10,budget:{max_nodes:20,max_ms:100}});expect(r.state).toBe('RESERVED');expect(r.mandatory_review_waivable).toBe(false);const s=settleStructuralCompute({root,taskId:'t',actualNodes:30,actualMs:10});expect(s.state).toBe('OVER_BUDGET_REVIEW_REQUIRED');});
test('integration receipt binding carries frontend and structural evidence hashes',()=>{const x=bindStructuralIntegrationEvidence({receipt:{receipt_id:'r'},unitMap:{structural_reality_map:{snapshot_hash:'s',normalized_graph_hash:'n',source_manifest_hash:'m',unit_structural_fingerprint:'f',frontend_projection_hash:'px'}},expectedObservedDelta:{delta_hash:'d'}});expect(x.structural).toMatchObject({snapshot_hash:'s',frontend_projection_hash:'px',expected_observed_delta_hash:'d',authority:'SUBORDINATE_STRUCTURAL_EVIDENCE'});});
test('incomplete extraction cannot hard-satisfy structural contracts',()=>{const p=JSON.parse(fs.readFileSync(path.join(repoDir,'agent-system/registries/STRUCTURAL_REALITY_POLICY.json'),'utf8'));const f=evaluateStructuralContracts({snapshot:{nodes:[],edges:[]},policy:p,extractionComplete:false});expect(f.every(x=>x.hard_satisfied===false&&x.state==='UNKNOWN_INCOMPLETE')).toBe(true);});
test('repository structural architecture gate is green',()=>{const r=checkStructuralArchitecture(repoDir);expect(r.status).toBe('GREEN');expect(r.checks).toHaveLength(16);});
