// @ts-nocheck -- native ESM orchestration modules intentionally have no declaration files.
import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  UNION_ALPHA_ROLES,
  runUnionAlphaResearchBatch,
  sanitizeUnionAlphaProviderPacket,
  validateUnionAlphaResult,
} from '../agent-system/orchestration/providers/openrouter/union-alpha-research-adapter.mjs';
import { buildResearchCoverageManifest, buildResearchHarvestManifest } from '../agent-system/orchestration/vekl-research-harvest.mjs';
import { COVERAGE_STATUSES, RESEARCH_DIMENSIONS, RESEARCH_POLARITIES, validateResearchContract } from '../agent-system/orchestration/vekl-research-contracts.mjs';
import { writeJsonAtomic } from '../agent-system/orchestration/state-store.mjs';

const packet = () => ({ schema_version: 1, mission_id: 'mission-12345678', batch_id: 'batch-12345678', batch_kind: 'UNIT_RESEARCH', data_class: 'PUBLIC_RESEARCH_ONLY', subjects: [{ subject_id: 'a'.repeat(24), topic: 'Public software topic', module_class: 'TEST', technology_tags: ['Node.js'], engineering_questions: UNION_ALPHA_ROLES.map((r) => `${r}: question`), role_scope: [...UNION_ALPHA_ROLES], source_hints: [{ source_id: 'official.node', authority: 'ENGINEERING_GUIDANCE_ONLY', url: 'https://nodejs.org/docs/latest/api/' }], search_queries: ['Node.js official current guidance'] }] });
function result(ref = 'official.node') { return { schema_version: 1, batch_id: 'batch-12345678', subjects: [{ subject_id: 'a'.repeat(24), roles: Object.fromEntries(UNION_ALPHA_ROLES.map((role) => [role, { findings: [{ claim: 'A bounded public claim', source_refs: [ref], confidence: 0.8, freshness_note: null }], risks: [], recommendations: [], unknowns: [] }])), cross_role_synthesis: { implementation_patterns: [], anti_patterns: [], verification_focus: [], unresolved_contradictions: [] } }], batch_contradictions: [] }; }

describe('VEKL Union Alpha harvest', () => {
  it('preserves every one of the 18 owner-named roles', () => { expect(UNION_ALPHA_ROLES).toHaveLength(18); expect(new Set(UNION_ALPHA_ROLES).size).toBe(18); });
  it('permits only public sanitized packets and strips private bindings', () => { const safe = sanitizeUnionAlphaProviderPacket(packet()); expect(safe.data_class).toBe('PUBLIC_RESEARCH_ONLY'); expect(JSON.stringify(safe)).not.toContain('unit_lineage_id'); expect(() => sanitizeUnionAlphaProviderPacket({ ...packet(), data_class: 'PRIVATE' })).toThrow('PUBLIC_RESEARCH_ONLY'); });
  it('rejects malformed output, missing roles and fabricated citations', () => { expect(validateUnionAlphaResult({}, packet()).ok).toBe(false); const missing = result(); delete missing.subjects[0].roles.SECURITY_RESEARCHER; expect(validateUnionAlphaResult(missing, packet()).reason).toContain('RESULT_ROLE_MISSING'); expect(validateUnionAlphaResult(result('https://fabricated.example/x'), packet()).reason).toContain('CITATION_NOT_IN_PACKET'); });
  it('fails closed before inference when the free window ended', async () => { const previous = process.env.DIAL_UNION_ALPHA_FREE_WINDOW_CLOSED; process.env.DIAL_UNION_ALPHA_FREE_WINDOW_CLOSED = '1'; let calls = 0; try { await expect(runUnionAlphaResearchBatch({ batch: packet(), root: '/tmp/dial-vekl-closed-test', fetchImpl: async () => { calls++; throw new Error('must not call network'); } })).rejects.toMatchObject({ category: 'FREE_WINDOW_CLOSED' }); expect(calls).toBe(0); } finally { if (previous == null) delete process.env.DIAL_UNION_ALPHA_FREE_WINDOW_CLOSED; else process.env.DIAL_UNION_ALPHA_FREE_WINDOW_CLOSED = previous; } });
  it('generates a deterministic exact 309-DU coverage manifest', () => { const a = buildResearchCoverageManifest(); const b = buildResearchCoverageManifest(); expect(a.coverage_manifest_hash).toBe(b.coverage_manifest_hash); expect(a.units).toHaveLength(309); expect(a.units[0].dimensions).toHaveProperty('SECURITY'); expect(Object.values(a.units[0].dimensions).every((x) => x.status === 'FAILED_BLOCKING')).toBe(true); expect(validateResearchContract('ResearchCoverageManifest', a).ok).toBe(true); });
  it('binds graph identity from the live control-state pointer with deterministic registry fallback', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'dial-vekl-harvest-')); try { const fallback = buildResearchHarvestManifest({ root }); expect(fallback.graph_generation_id).toBeNull(); expect(fallback.graph_revision_hash).toBeNull(); writeJsonAtomic('knowledge/graph/current.json', { graph_generation_id: 'KG-live-test', graph_revision_hash: 'revision-live-test' }, root); const mission = buildResearchHarvestManifest({ root }); const coverage = buildResearchCoverageManifest({ root }); expect(mission).toMatchObject({ graph_generation_id: 'KG-live-test', graph_revision_hash: 'revision-live-test' }); expect(coverage).toMatchObject({ graph_generation_id: 'KG-live-test', graph_revision_hash: 'revision-live-test' }); } finally { fs.rmSync(root, { recursive: true, force: true }); } });
  it('binds mission lineage, hashes, exact model, no fallback, dimensions, statuses and polarities', () => { const mission = buildResearchHarvestManifest(); expect(mission.repository_sha).toMatch(/^[a-f0-9]{40}$/); expect(mission.provider_binding).toMatchObject({ provider: 'openrouter', model_id: 'stealth/union-alpha', fallback: 'PROHIBITED', paid_inference: 'PROHIBITED' }); expect(mission.required_roles).toEqual(UNION_ALPHA_ROLES); expect(RESEARCH_DIMENSIONS).toHaveLength(17); expect(COVERAGE_STATUSES).toContain('ADMITTED'); expect(RESEARCH_POLARITIES).toEqual(expect.arrayContaining(['ANTI_PATTERN', 'SECURITY_WARNING', 'DEPRECATED'])); });
});
